environments:
  {{ .Environment.Name }}:
    values:
      - environments/{{ .Environment.Name }}-values.yaml

releases:
  - name: helmfile-envoy-{{ .Values.stage }}
    namespace: helmfile-envoy-{{ .Environment.Name }}
    chart: stable/envoy
    values:
      - values.yaml.gotmpl
